name: Windows Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: z

      - name: Enable Long Paths
        run: |
          reg add HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f
        shell: cmd

      - name: Enable Git long paths
        run: git config --system core.longpaths true

      - name: Set CARGO_HOME
        run: echo "CARGO_HOME=C:/cargo" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Zed
        working-directory: ./z
        run: cargo build --release